### ISSUE TITLE
Skills

### ISSUE THREAD

**Issue by Xorck** [HeyHeyChicken/NOVA-Python#1]
Bonjour Chicken,

Qu'elles sont les skills de base de Nova?

**Comment by HeyHeyChicken** [comment]
Bonjour @Xorck,

Je suis désolé, je n'ai pas remarqué la notification (et à vrai dire, tu es la première personne avec laquelle je communique via ce canal.
Les skills de cette version de Nova se trouvent ici :
https://github.com/HeyHeyChicken/NOVA-Python/tree/main/src/plugins
Il peut converser, compter, donner la date et l'heure, fournir son IP, jouer de la lumière si l'on dispose du HAT compatible, chercher du contenu sur mediastack, lancer un dé, un timer et enfin, régler le volume à la voix.

Bonne journée :)
